name: Publish on GitHub Pages
on:
  push:
    branches: [trunk]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Deno environment
        uses: denoland/setup-deno@v2
        with:
          cache: true

      - name: Build site
        # Asume que tienes una tarea llamada 'build' en tu deno.json o Deno.jsonc
        run: deno task build
